# Setup
title:        People Of NITH
tagline:      NITH's Student Website That Was So Direly Needed
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Arihant Verma
  url:        https://twitter.com/gdad_s_river

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown